inputs:
  anthropic_api_key:
    description: Anthropic API key for Claude
    required: true

runs:
  using: composite

  steps:
    - uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        additional_permissions: |
          actions: read
        claude_args: |
          --add-dir "${{ github.action_path }}/../../.."
          --append-system-prompt "
            Read @${{ github.action_path }}/../../../.agents/rules/shared/AGENTS.md for organizational guidelines.
          "
