inputs:
  anthropic_api_key:
    description: Anthropic API key for Claude
    required: true

runs:
  using: composite

  steps:
    - shell: bash
      id: checkout-pr
      run: |
        gh pr checkout ${{ github.event.pull_request.number || github.event.issue.number }}

        # Extract just the file path from the workflow ref (format: owner/repo/.github/workflows/file.yml@ref).
        workflow_file_path="$(
          echo "${{ github.workflow_ref }}" | sed -E 's|.*/.github/workflows/([^@]*).*|.github/workflows/\1|'
        )"

        if gh pr diff --name-only | grep -F "$workflow_file_path"; then
          echo "workflow-changed=true" >> $GITHUB_OUTPUT
          echo "::notice::Current workflow file ($workflow_file_path) changed - skipping review"
        else
          echo "workflow-changed=false" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: anthropics/claude-code-action@v1
      env:
        GH_API_COMMENTS_COMMAND: >-
          ${{ github.action_path }}/gh-pr-comments.sh
          ${{ github.event.pull_request.number || github.event.issue.number }}
      # `claude-code-action` fails if the workflow file changes.
      if: steps.checkout-pr.outputs.workflow-changed != 'true'
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}

        prompt: |
          REPO: ${{ github.repository }}
          PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}

          Please conduct a thorough code review of this pull request.
          Make sure to follow the guidelines in @${{ github.action_path }}/../../../.agents/rules/shared/code-review.md

          Note: The PR branch is already checked out in the current working directory.

          IMPORTANT: Before starting your review, read the details including reviews and inline comments
          (use exactly these commands, do not substitute variables):
          ```
          gh pr view --json title,body,files,additions,deletions,comments
          ${{ env.GH_API_COMMENTS_COMMAND }}
          ```

          Check for any issues that have already been identified by previous reviews.
          Only comment on new issues that haven't been previously noted.

          ${{
            github.event.comment
            && format('
              User provided additional context for this review:
              ```
              {0}
              ```
            ', github.event.comment.body)
            || ''
          }}

          Apply your standard review process, covering all relevant areas including code quality, documentation
          accuracy, content quality, and structural organization according to your established review priorities.

          Use `gh pr comment:*` for top-level comments.
          Use `mcp__github_inline_comment__create_inline_comment` to highlight specific areas of concern.
          Only your GitHub comments that you post will be seen,
          so don't submit your review as a normal message, just as comments.
          If all issues have been addressed or already noted,
          post a brief note like "✅ Review complete - no new issues found".

        claude_args: |
          --add-dir "${{ github.action_path }}/../../.."
          --append-system-prompt "
            Read @${{ github.action_path }}/../../../.agents/rules/shared/AGENTS.md for organizational guidelines.
          "
          --allowedTools "
            mcp__github_ci__get_ci_status,
            mcp__github_ci__get_workflow_run_details,
            mcp__github_ci__download_job_log,
            mcp__github_inline_comment__create_inline_comment,
            Bash(gh pr comment:*),
            Bash(gh pr diff:*),
            Bash(gh pr view:*),
            Bash(${{ env.GH_API_COMMENTS_COMMAND }}),
          "
