name: deploy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@mdbook

      - run: mdbook build

      - uses: actions/upload-artifact@v4
        with:
          name: book
          path: book
          if-no-files-found: error
          retention-days: 1
