name: deploy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: read

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@mdbook

      - id: pages
        uses: actions/configure-pages@v5

      - run: mdbook build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: book

  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
