name: editorconfig-checker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  editorconfig-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false
      - run: go install github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker@latest
      - run: editorconfig-checker -f github-actions -no-color
