name: yamllint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: pipx run yamllint .
